# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository
          - npm install --also=dev --no-audit
          - npm run build
          - npm run test

          # commit changes, if any (all allowed to fail)
          - git add . || true
          - git commit -m "[skip ci] Bot automatically compiles typescript" || true
          - git push || true
